(*
{$define USE_FONT_4X6}
{$define  USE_FONT_5X8}
{$define  USE_FONT_5X12}
{$define  USE_FONT_6X8}
{$define  USE_FONT_6X10}
{$define  USE_FONT_7X12}
{$define  USE_FONT_8X8}
{$define  USE_FONT_8X12_CYRILLIC}
{$define  USE_FONT_8X12}
*)
{$define  USE_FONT_8X14}
(*
{$define  USE_FONT_10X16}
{$define  USE_FONT_12X16}
{$define  USE_FONT_12X20}
*)
{$define  USE_FONT_16X26}
(*
{$define  USE_FONT_22X36}
{$define  USE_FONT_24X40}
{$define  USE_FONT_32X53}
*)
